version: "3.5"
services:
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    depends_on:
      - web
    networks:
      - app-net
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Dockerfile-debug
    container_name: web
    command: java -jar /app/app.jar
    depends_on:
      - keycloak
      - db
    networks:
      - app-net
    restart: on-failure

  keycloak:
    image: jboss/keycloak:9.0.3
    container_name: keycloak
    depends_on:
      - db
    networks:
      - app-net
    restart: on-failure

  db:
    image: postgres:12.2
    container_name: db
    networks:
      - app-net
    restart: on-failure

networks:
  app-net:
