version: "3.5"
services:
  nginx:
    ports:
      - target: 8000
        published: 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

  web:
    environment:
      - PARAMS_KEYCLOAK_URL=http://keycloak:8080
      - PARAMS_DB_URL=db:5432
      - PARAMS_DB_NAME=web
      - PARAMS_DB_USERNAME=admin
      - PARAMS_DB_PASSWORD=admin
    volumes:
      - ./horarios:/app/horarios/

  keycloak:
    ports:
      - target: 8080
        published: 8180
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - "KEYCLOAK_IMPORT=/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
      - DB_ADDR=db
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json

  db:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=web,keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - target: 5432
        published: 5432
    volumes:
      - ./postgres/pg-init-scripts:/docker-entrypoint-initdb.d
