version: "3.5"
services:
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    depends_on:
      - backend-web
      - horario-web
    networks:
      - app-net
    restart: always

  backend-web:
    build:
      context: .
      dockerfile: Dockerfile-debug
    container_name: backend-web
    command: java -jar /app/app.jar
    depends_on:
      - keycloak
      - backend-db
      - horario-web
    networks:
      - app-net
    restart: always

  backend-db:
    image: postgres:12.2
    container_name: backend-db
    networks:
      - app-net
    restart: always

  keycloak:
    image: jboss/keycloak:9.0.3
    container_name: keycloak
    depends_on:
      - keycloak-db
    networks:
      - app-net
    restart: always

  keycloak-db:
    image: postgres:12.2
    container_name: keycloak-db
    networks:
      - app-net
    restart: always

  horario-web:
    build:
      context: ../poliplanner-horario/
      dockerfile: Dockerfile-debug
    container_name: horario-web
    command: java -jar /app/app.jar
    depends_on:
      - keycloak
      - horario-db
    networks:
      - app-net
    restart: always

  horario-db:
    image: postgres:12.2
    container_name: horario-db
    networks:
      - app-net
    restart: always

networks:
  app-net:
