FROM maven:3.6.3-jdk-11 AS debug
RUN mkdir source
WORKDIR /source
ADD . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests
RUN mvn clean package -DskipTests
WORKDIR /
RUN mkdir app
WORKDIR /app
RUN cp /source/target/app.jar .