version: "3.5"
services:
  nginx:
    ports:
      - target: 8000
        published: 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

  backend-web:
    environment:
      - PARAMS_KEYCLOAK_URL=http://keycloak:8080
      - PARAMS_DB_URL=backend-db:5432
      - PARAMS_DB_NAME=backend-web
      - PARAMS_DB_USERNAME=admin
      - PARAMS_DB_PASSWORD=admin
      - PARAMS_HORARIO_URL=http://horario-web:8080

  backend-db:
    environment:
      - POSTGRES_DB=backend-web
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - target: 5432
        published: 5432

  horario-web:
    environment:
      - PARAMS_KEYCLOAK_URL=http://keycloak:8080
      - PARAMS_DB_URL=horario-db:5432
      - PARAMS_DB_NAME=horario-web
      - PARAMS_DB_USERNAME=admin
      - PARAMS_DB_PASSWORD=admin
    volumes:
      - ./horarios:/app/horarios/

  horario-db:
    environment:
      - POSTGRES_DB=horario-web
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - target: 5432
        published: 5433

  keycloak:
    ports:
      - target: 8080
        published: 8180
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - "KEYCLOAK_IMPORT=/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
      - DB_ADDR=keycloak-db
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - ./keycloak/realm.json:/tmp/realm.json

  keycloak-db:
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - target: 5432
        published: 5434