FROM maven:3.6.3-jdk-11 AS appserver
COPY ./.m2 /root/.m2/repository
RUN mkdir source
WORKDIR /source
ADD . .
RUN mvn -B package -DskipTests

FROM adoptopenjdk/openjdk11:alpine-jre AS debug
RUN mkdir app
WORKDIR /app
COPY --from=appserver /source/target/app.jar .