auth-server:
  url: http://localhost:8083
  realm-name: poliplanner
spring:
  profiles:
    active:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server.url}/auth/realms/${auth-server.realm-name}
          jwk-set-uri: ${auth-server.url}/auth/realms/${auth-server.realm-name}/protocol/openid-connect/certs
